2016-06-24 16:30:55,641 [Thread-2:20660] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2016-06-28 16:20:10,137 [Thread-2:11816] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2016-06-28 16:20:16,836 [Thread-11:12384] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Django\Myblog\blog\views.py", line 72, in index
    return render(request, 'index.html', locals())
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 208, in render
    with context.bind_template(self):
  File "C:\Python27\Lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "D:\Django\blog_project_venv\lib\site-packages\debug_toolbar\panels\templates\panel.py", line 79, in _request_context_bind_template
    context = processor(self.request)
  File "C:\Python27\lib\site-packages\django\utils\decorators.py", line 127, in _wrapped_view
    return middleware.process_response(request, response)
  File "C:\Python27\lib\site-packages\django\middleware\cache.py", line 78, in process_response
    if response.streaming or response.status_code != 200:
AttributeError: 'dict' object has no attribute 'streaming'
2016-06-28 16:24:09,842 [Thread-3:21484] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2016-06-28 16:24:14,539 [Thread-2:22188] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Django\Myblog\blog\views.py", line 72, in index
    return render(request, 'index.html', locals())
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 208, in render
    with context.bind_template(self):
  File "C:\Python27\Lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\Python27\lib\site-packages\django\template\context.py", line 235, in bind_template
    updates.update(processor(self.request))
  File "C:\Python27\lib\site-packages\django\utils\decorators.py", line 127, in _wrapped_view
    return middleware.process_response(request, response)
  File "C:\Python27\lib\site-packages\django\middleware\cache.py", line 78, in process_response
    if response.streaming or response.status_code != 200:
AttributeError: 'dict' object has no attribute 'streaming'
2016-06-28 16:24:54,234 [Thread-2:25064] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Django\Myblog\blog\views.py", line 72, in index
    return render(request, 'index.html', locals())
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 208, in render
    with context.bind_template(self):
  File "C:\Python27\Lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\Python27\lib\site-packages\django\template\context.py", line 235, in bind_template
    updates.update(processor(self.request))
  File "C:\Python27\lib\site-packages\django\utils\decorators.py", line 127, in _wrapped_view
    return middleware.process_response(request, response)
  File "C:\Python27\lib\site-packages\django\middleware\cache.py", line 78, in process_response
    if response.streaming or response.status_code != 200:
AttributeError: 'dict' object has no attribute 'streaming'
2016-06-28 16:28:59,265 [Thread-2:26964] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Django\Myblog\blog\views.py", line 72, in index
    return render(request, 'index.html', locals())
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 208, in render
    with context.bind_template(self):
  File "C:\Python27\Lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\Python27\lib\site-packages\django\template\context.py", line 235, in bind_template
    updates.update(processor(self.request))
  File "C:\Python27\lib\site-packages\django\utils\decorators.py", line 127, in _wrapped_view
    return middleware.process_response(request, response)
  File "C:\Python27\lib\site-packages\django\middleware\cache.py", line 78, in process_response
    if response.streaming or response.status_code != 200:
AttributeError: 'dict' object has no attribute 'streaming'
2016-06-28 16:36:44,927 [Thread-2:12824] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2016-06-28 16:36:51,816 [Thread-3:25420] [django.request:170] [base:get_response] [WARNING]- Not Found: /INdex
2016-06-28 16:39:33,282 [Thread-2:18212] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2016-06-28 16:39:38,290 [Thread-3:25192] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Django\Myblog\blog\views.py", line 74, in index
    return render(request, 'index.html', locals())
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 208, in render
    with context.bind_template(self):
  File "C:\Python27\Lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "D:\Django\blog_project_venv\lib\site-packages\debug_toolbar\panels\templates\panel.py", line 79, in _request_context_bind_template
    context = processor(self.request)
  File "C:\Python27\lib\site-packages\django\utils\decorators.py", line 127, in _wrapped_view
    return middleware.process_response(request, response)
  File "C:\Python27\lib\site-packages\django\middleware\cache.py", line 78, in process_response
    if response.streaming or response.status_code != 200:
AttributeError: 'dict' object has no attribute 'streaming'
